---
apiVersion: v1
kind: Service
metadata:
  name: grpc-api
spec:
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: grpc-api
  ports:
    - name:
      protocol: TCP
      port: 9080
      # targetPort: 80
  clusterIP: None
